# vim ft=yaml
# travis-ci.org definition for MOxUnit build (based on CoSMoMVPA,
# which is based on PyMVPA, which is based on nipype configuration, 
# which in turn was based on nipy)
#
# We pretend to be java because we need GNU Octave which is not
# available (as of April 2015)

language: java

cache:
  
  apt: true # Not working for public repos :( 
  directories:
    # Following directories will be generated 
    - $HOME/octave
    - $HOME/build/neuropoly/qMRLab/octPacks
    - $HOME/build/neuropoly/qMRLab/osfData
env:
 global:
    - OCTAVE=octave
before_install:
    # to prevent IPv6 being used for APT
    language: OCTAVE
    - sudo bash -c "echo 'Acquire::ForceIPv4 \"true\";' > /etc/apt/apt.conf.d/99force-ipv4"
    - travis_retry sudo apt-get -y -qq update
    - travis_retry sudo apt-get install -y -qq software-properties-common python-software-properties
    - travis_retry sudo apt-add-repository -y ppa:octave/stable
    - travis_retry sudo apt-get -y -qq update
    # travis_retry sudo apt-get install -y wget
    # get Octave 4,0
    - travis_retry sudo apt-get -y -qq install octave liboctave-dev octave-pkg-dev
    # Please comment in following section if you need to update packages or add a new one
    # If following section is going to be commented in, please set cacheState to false in startup.m
    # --------------
    #- travis_retry wget http://sourceforge.net/projects/octave/files/Octave%20Forge%20Packages/Individual%20Package%20Releases/struct-1.0.14.tar.gz -P /home/travis/build/neuropoly/qMRLab/octPacks
    #- travis_retry wget http://sourceforge.net/projects/octave/files/Octave%20Forge%20Packages/Individual%20Package%20Releases/optim-1.5.2.tar.gz -P /home/travis/build/neuropoly/qMRLab/octPacks
    #- travis_retry wget https://sourceforge.net/projects/octave/files/Octave%20Forge%20Packages/Individual%20Package%20Releases/io-2.4.10.tar.gz -P /home/travis/build/neuropoly/qMRLab/octPacks
    #- travis_retry wget http://sourceforge.net/projects/octave/files/Octave%20Forge%20Packages/Individual%20Package%20Releases/statistics-1.3.0.tar.gz -P /home/travis/build/neuropoly/qMRLab/octPacks
    #- travis_retry wget http://sourceforge.net/projects/octave/files/Octave%20Forge%20Packages/Individual%20Package%20Releases/image-2.6.1.tar.gz -P /home/travis/build/neuropoly/qMRLab/octPacks
    # --------------
matrix:
  include:
  - name: Build with foo as bar
  
jobs:
  include:
    - stage: Test
      script: travis_wait 10 octave --no-gui --eval "startup;cd('Test/MoxUnitCompatible/quickMoxTests');res=moxunit_runtests('-recursive');exit(~res);"
    - stage: Test
      script: travis_wait 30 octave --no-gui --eval "startup;cd('Test/MoxUnitCompatible');res=moxunit_runtests('BatchExample_test.m');exit(~res);"
    - stage: Test
      script: travis_wait 30 octave --no-gui --eval "startup;cd('Test/MoxUnitCompatible');res=moxunit_runtests('Sim_test.m');exit(~res);"

  

